use std::sync::Mutex;
use aes_gcm::aead::{Aead, KeyInit, OsRng, Payload};
use aes_gcm::{Aes256Gcm, Nonce};
use rand::RngCore;
use zeroize::Zeroize;

/// Errors produced by secret-store encryption and key management.
#[derive(Debug, thiserror::Error)]
pub enum SecretEncryptionError {
    #[error("keychain error: {0}")]
    Keychain(String),

    #[error("encryption error: {0}")]
    Encryption(String),

    #[error("vault data corrupted: {0}")]
    Corrupted(String),
}

/// Provides a 256-bit master encryption key, typically backed by the OS keychain.
pub trait MasterKeyProvider: Send + Sync {
    fn get_or_create_key(&self) -> Result<[u8; 32], SecretEncryptionError>;
    fn delete_key(&self) -> Result<(), SecretEncryptionError>;
    fn provider_name(&self) -> &str;
}

/// Encrypt `plaintext` with AES-256-GCM, returning `nonce || ciphertext`.
pub fn encrypt(key: &[u8; 32], plaintext: &[u8]) -> Result<Vec<u8>, SecretEncryptionError> {
    encrypt_with_aad(key, plaintext, &[])
}

/// Encrypt bytes with AES-256-GCM and caller-supplied associated data.
///
/// The returned representation is `nonce || ciphertext || tag`. The nonce is
/// generated by the operating system RNG for every invocation and is never
/// accepted from a caller.
pub fn encrypt_with_aad(
    key: &[u8; 32],
    plaintext: &[u8],
    aad: &[u8],
) -> Result<Vec<u8>, SecretEncryptionError> {
    let cipher = Aes256Gcm::new_from_slice(key)
        .map_err(|e| SecretEncryptionError::Encryption(e.to_string()))?;

    let mut nonce_bytes = [0u8; 12];
    OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from(nonce_bytes);

    let ciphertext = cipher
        .encrypt(
            &nonce,
            Payload {
                msg: plaintext,
                aad,
            },
        )
        .map_err(|e| SecretEncryptionError::Encryption(e.to_string()))?;

    let mut out = Vec::with_capacity(12 + ciphertext.len());
    out.extend_from_slice(&nonce_bytes);
    out.extend_from_slice(&ciphertext);
    Ok(out)
}

/// Decrypt data produced by [`encrypt`].
pub fn decrypt(key: &[u8; 32], data: &[u8]) -> Result<Vec<u8>, SecretEncryptionError> {
    decrypt_with_aad(key, data, &[])
}

/// Decrypt bytes produced by [`encrypt_with_aad`]. A wrong key, altered AAD,
/// nonce reuse substitution or ciphertext corruption all fail closed with the
/// same payload-free corruption error.
pub fn decrypt_with_aad(
    key: &[u8; 32],
    data: &[u8],
    aad: &[u8],
) -> Result<Vec<u8>, SecretEncryptionError> {
    if data.len() < 12 {
        return Err(SecretEncryptionError::Corrupted(
            "ciphertext too short to contain nonce".into(),
        ));
    }

    let (nonce_bytes, ciphertext) = data.split_at(12);
    let nonce = Nonce::from(<[u8; 12]>::try_from(nonce_bytes).map_err(|_| {
        SecretEncryptionError::Corrupted("ciphertext nonce length must be 12 bytes".into())
    })?);

    let cipher = Aes256Gcm::new_from_slice(key)
        .map_err(|e| SecretEncryptionError::Encryption(e.to_string()))?;

    cipher
        .decrypt(
            &nonce,
            Payload {
                msg: ciphertext,
                aad,
            },
        )
        .map_err(|_| SecretEncryptionError::Corrupted("AES-GCM authentication failed".into()))
}

/// Ephemeral key provider that holds the master key in process memory.
pub struct InMemoryKeyProvider {
    key: Mutex<Option<[u8; 32]>>,
}

impl InMemoryKeyProvider {
    pub fn new() -> Self {
        Self {
            key: Mutex::new(None),
        }
    }
}

impl Default for InMemoryKeyProvider {
    fn default() -> Self {
        Self::new()
    }
}

impl MasterKeyProvider for InMemoryKeyProvider {
    fn get_or_create_key(&self) -> Result<[u8; 32], SecretEncryptionError> {
        let mut guard = self.key.lock().map_err(|e| {
            SecretEncryptionError::Keychain(format!("in-memory key mutex poisoned: {e}"))
        })?;

        if let Some(existing) = *guard {
            return Ok(existing);
        }

        let mut key = [0u8; 32];
        rand::rngs::OsRng.fill_bytes(&mut key);
        *guard = Some(key);
        Ok(key)
    }

    fn delete_key(&self) -> Result<(), SecretEncryptionError> {
        let mut guard = self.key.lock().map_err(|e| {
            SecretEncryptionError::Keychain(format!("in-memory key mutex poisoned: {e}"))
        })?;

        if let Some(ref mut k) = *guard {
            k.zeroize();
        }
        *guard = None;
        Ok(())
    }

    fn provider_name(&self) -> &str {
        "in_memory"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encrypt_round_trip() {
        let key = [7u8; 32];
        let plaintext = b"top-secret";

        let encrypted = encrypt(&key, plaintext).unwrap();
        let decrypted = decrypt(&key, &encrypted).unwrap();

        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn wrong_key_fails() {
        let key_a = [1u8; 32];
        let key_b = [2u8; 32];

        let encrypted = encrypt(&key_a, b"secret").unwrap();

        assert!(matches!(
            decrypt(&key_b, &encrypted),
            Err(SecretEncryptionError::Corrupted(_))
        ));
    }

    #[test]
    fn corrupted_ciphertext_fails_without_panic() {
        let key = [5u8; 32];
        let encrypted = encrypt(&key, b"secret").unwrap();
        let mut corrupted = encrypted;
        corrupted[12] ^= 0xFF;

        assert!(matches!(
            decrypt(&key, &corrupted),
            Err(SecretEncryptionError::Corrupted(_))
        ));
    }

    #[test]
    fn aad_is_authenticated_and_nonces_are_unique() {
        let key = [9u8; 32];
        let first = encrypt_with_aad(&key, b"personal-record", b"scope-a/install-a/r1").unwrap();
        let second = encrypt_with_aad(&key, b"personal-record", b"scope-a/install-a/r1").unwrap();

        assert_ne!(&first[..12], &second[..12]);
        assert_eq!(
            decrypt_with_aad(&key, &first, b"scope-a/install-a/r1").unwrap(),
            b"personal-record"
        );
        assert!(matches!(
            decrypt_with_aad(&key, &first, b"scope-b/install-a/r1"),
            Err(SecretEncryptionError::Corrupted(_))
        ));
    }

    #[test]
    fn in_memory_provider_is_stable_until_delete() {
        let provider = InMemoryKeyProvider::new();

        let first = provider.get_or_create_key().unwrap();
        let second = provider.get_or_create_key().unwrap();

        assert_eq!(first, second);
    }

    #[test]
    fn in_memory_provider_delete_regenerates() {
        let provider = InMemoryKeyProvider::new();

        let first = provider.get_or_create_key().unwrap();
        provider.delete_key().unwrap();
        let second = provider.get_or_create_key().unwrap();

        assert_ne!(first, second);
    }
}
